version: '3.7'

services:
  app:
    container_name: backgazin
    image: node-backgazin
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app